// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAodoZQqvtlYK7Z0DVTuBlQ4TRNSE2QFjw',
    appId: '1:841826973228:web:16228e5f92cb691dd3c389',
    messagingSenderId: '841826973228',
    projectId: 'smartrent-ba411',
    authDomain: 'smartrent-ba411.firebaseapp.com',
    storageBucket: 'smartrent-ba411.firebasestorage.app',
    measurementId: 'G-4MWKT570XY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-YJqk1P-kPnrqpBqxc6l_P2eQRk8Ad-8',
    appId: '1:841826973228:android:8a6678e327c14354d3c389',
    messagingSenderId: '841826973228',
    projectId: 'smartrent-ba411',
    storageBucket: 'smartrent-ba411.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOiJD6q9v9RhuZ4ZD_ot2TOu9hNku5YsA',
    appId: '1:841826973228:ios:542c820545f9c9edd3c389',
    messagingSenderId: '841826973228',
    projectId: 'smartrent-ba411',
    storageBucket: 'smartrent-ba411.firebasestorage.app',
    iosBundleId: 'com.example.smartRent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOiJD6q9v9RhuZ4ZD_ot2TOu9hNku5YsA',
    appId: '1:841826973228:ios:542c820545f9c9edd3c389',
    messagingSenderId: '841826973228',
    projectId: 'smartrent-ba411',
    storageBucket: 'smartrent-ba411.firebasestorage.app',
    iosBundleId: 'com.example.smartRent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAodoZQqvtlYK7Z0DVTuBlQ4TRNSE2QFjw',
    appId: '1:841826973228:web:94244589e651aa8cd3c389',
    messagingSenderId: '841826973228',
    projectId: 'smartrent-ba411',
    authDomain: 'smartrent-ba411.firebaseapp.com',
    storageBucket: 'smartrent-ba411.firebasestorage.app',
    measurementId: 'G-VNE15J25VZ',
  );
}
